# Generated by Django 5.1.6 on 2025-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filesize',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('txt', 'Texte'), ('image', 'Image')], default='txt', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
