# Generated by Django 5.1.6 on 2025-02-24 14:11

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.user_directory_path),
        ),
    ]
