# Generated by Django 5.1.6 on 2025-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desktop", "0006_alter_file_options_alter_file_filename_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AlterField(
            model_name="file",
            name="filename",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="file",
            name="filesize",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
